### ISSUE TITLE
如果iframe postMessage 报错 跨域怎么办呢

### ISSUE THREAD

**Issue by starplatinum3** [zhaodeezhu/xioo#3]
我看好像是有跨域，但是我好像跨域不成功，是iframe跨域，cors配置可以吗
```js
 /** 启动app */

  start(port: number = this.config.http.port) {

    this.server.use(cors({

      maxAge: 1800

    }) as any);
```

因为这个项目我想在前端发iframe给[xioo-docs](https://github.com/zhaodeezhu/xioo-docs)，但是跨域错了
https://github.com/zhaodeezhu/xioo-docs
```js
 getIframeWin(){
      if(  this.iframeWin==null){
        this. iframeWin = this.$refs.myframe?.contentWindow
      }
    return    this. iframeWin
   
    },
 iframeWin.postMessage(
        data,
        "*"
      );
```

**Comment by zhaodeezhu** [comment]
把报错信息发出来看下

**Comment by starplatinum3** [comment]
Uncaught DOMException: Blocked a frame with origin "http://10.61.186.236:8088" from accessing a cross-origin frame.
    at et (http://10.61.186.236:8088/static/js/chunk-vendors.a304166b.js:26:9567)
    at Object.get [as iframeWin] (http://10.61.186.236:8088/static/js/chunk-vendors.a304166b.js:26:8793)
    at Vr.Fr.get [as iframeWin] (http://10.61.186.236:8088/static/js/chunk-vendors.a304166b.js:26:41442)
    at a.sendMegToIframe (http://10.61.186.236:8088/static/js/chunk-25c43fe5.f5fe1de5.js:1:159257)
    at http://10.61.186.236:8088/static/js/chunk-25c43fe5.f5fe1de5.js:1:159656
et @ chunk-vendors.a304166b.js:26
get @ chunk-vendors.a304166b.js:26
Vr.Fr.get @ chunk-vendors.a304166b.js:26
sendMegToIframe @ chunk-25c43fe5.f5fe1de5.js:1
(匿名) @ chunk-25c43fe5.f5fe1de5.js:1
setTimeout(异步)
docShow @ chunk-25c43fe5.f5fe1de5.js:1
Bn @ chunk-vendors.a304166b.js:26
n @ chunk-vendors.a304166b.js:26
Bn @ chunk-vendors.a304166b.js:26
Pi.e.$emit @ chunk-vendors.a304166b.js:26
handleClick @ chunk-vendors.a304166b.js:43
Bn @ chunk-vendors.a304166b.js:26
n @ chunk-vendors.a304166b.js:26
Ia.o._wrapper @ chunk-vendors.a304166b.js:26
index.156185b6.js:1

**Comment by starplatinum3** [comment]
我试了下好像直接往drawio发postMessage是没有报错的，可能是drawio有做跨域

**Comment by zhaodeezhu** [comment]
![image](https://user-images.githubusercontent.com/58294623/230251167-765d69b7-2642-4d72-8686-c51603f2d9bf.png)
你这个服务是部署的drawio吗，是我的那个drawio-node项目本地启动吗

**Comment by starplatinum3** [comment]
这是我的一个前端，想要在iframe里面调用你的xioo-docs  
https://gitee.com/-/ide/project/starplatinum111/exam-vue-student/edit/master/-/src/views/exam/paper/do.vue
xioo-docs   - > 到 drawio-node的跨域是没问题的，但是我的前端到xioo-docs 的跨域有问题
